name: Security CI (Terraform + OPA)

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-security:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform/envs/demo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::767828729088:role/github-actions-terraform-role
          aws-region: us-east-1

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Run gitleaks (secrets scan)
        uses: gitleaks/gitleaks-action@v2
        

      - name: IaC scan (Checkov)
        run: |
          checkov -d terraform \
            --framework terraform \
            --skip-check CKV_AWS_144,CKV2_AWS_62,CKV2_AWS_11,CKV_AWS_356,CKV_AWS_111,CKV_AWS_109

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Export plan JSON
        run: terraform show -json tfplan > tfplan.json

      - name: Setup Conftest (OPA)
        uses: instrumenta/conftest-action@v0.4.0
        with:
          version: 0.56.0

      - name: OPA Conftest evaluate Terraform plan
        run: conftest test tfplan.json -p ../../policies/terraform

      - name: Upload evidence artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compliance-evidence
          path: |
            terraform/envs/demo/tfplan.json
            terraform/envs/demo/tfplan
